FROM temporalio/auto-setup:1.28.3

COPY temporal-cluster/server/dynamicconfig.yaml /etc/temporal/dynamicconfig.yaml
COPY temporal-cluster/server/dynamicconfig_es.yaml /etc/temporal/dynamicconfig_es.yaml
COPY temporal-cluster/server/config_template.yaml /etc/temporal/config/config_template.yaml
COPY temporal-cluster/server/.bashrc /home/temporal/.bashrc
